### ISSUE TITLE
添加 SelectDialog 组件

### ISSUE THREAD

**Issue by shinima** [shinima/aspp#7]
目前工具只支持如下图所示的确认框：

![image](https://user-images.githubusercontent.com/5550931/42411014-a7da4398-8226-11e8-9a67-ad3b9caf4921.png)

在一些时候，例如关闭未保存文件时，下图这样的确认框更为合适：

![image](https://user-images.githubusercontent.com/5550931/42411018-bbcdf4c6-8226-11e8-9b70-dfc1c804974b.png)

工具需要支持多个按钮的对话框。该对话框可以取名 `SelectDialog`，接受一个 `options: string[]` 表示可用的选项有哪些。另外需要实现一个对应的 saga，saga 返回值为用户选择的 option。实现完成之后，关闭未保存文件代码大致如下：

```javascript
const option = yield selectDialogSaga('是否需要保存修改？', ['save', 'do not save', 'cancel'])
```

**Comment by mwindson** [comment]
已实现
