### ISSUE TITLE
关闭文件时的一些建议

### ISSUE THREAD

**Issue by wemmaling** [shinima/aspp#8]
- [ ] 现在只有在手动点击"x"按钮时才会出现弹窗，建议在双击打开其他文件时也增加弹窗显示

- [ ] 关闭按钮点击率不高，建议放在右上角

**Comment by shinima** [comment]
> 现在只有在手动点击"x"按钮时才会出现弹窗，建议在双击打开其他文件时也增加弹窗显示

这个目前应该算是完成了，还有类似的地方也会慢慢优化

> 关闭按钮点击率不高，建议放在右上角

这个是个小问题，以后 UI 调整（如果有的话）的时候会重新考虑各个按钮的位置的。
